# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Website of David Brown
email: davidb@davidb.org
description: > # this means to ignore newlines until "baseurl:"
  Information and ramblings by David Brown on software, Jazz and
  various random things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidb.org" # the base hostname & protocol for your site
twitter_username: d3zd3z
github_username:  d3zd3z

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
